import 'package:app/controllers/competition/date.dart';
import 'package:app/models/composition.dart';

final JoueurComposition kRemplComposition = JoueurComposition(
    idComposition: 'R0' + DateController.dateCollapsed,
    left: 0,
    top: 0,
    idJoueur: 'joueur',
    numero: 0,
    isIn: false,
    nom: 'rempl0',
    idGame: 'game',
    idParticipant: 'equipe');
List<JoueurComposition> kRempl = [
  JoueurComposition(
      idComposition: 'R1' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl0',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      idComposition: 'R2' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl1',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      idComposition: 'R3' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl2',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      idComposition: 'R4' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl3',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      idComposition: 'R5' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl4',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      idComposition: 'R6' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur7',
      numero: 0,
      isIn: false,
      nom: 'rempl5',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      idComposition: 'R7' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl6',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      idComposition: 'R8' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur9',
      numero: 0,
      isIn: false,
      nom: 'rempl7',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      idComposition: 'R9' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl8',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      idComposition: 'R10' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl9',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      idComposition: 'R11' + DateController.dateCollapsed,
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl10',
      idGame: 'game',
      idParticipant: 'equipe'),
];
