import 'package:app/models/composition.dart';

final JoueurComposition kRemplComposition = JoueurComposition(
    left: 0,
    top: 0,
    idJoueur: 'joueur',
    numero: 0,
    isIn: false,
    nom: 'rempl0',
    idGame: 'game',
    idParticipant: 'equipe');
List<JoueurComposition> kRempl = [
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl0',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl1',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl2',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl3',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl4',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl5',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl6',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl7',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl8',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl9',
      idGame: 'game',
      idParticipant: 'equipe'),
  JoueurComposition(
      left: 0,
      top: 0,
      idJoueur: 'joueur',
      numero: 0,
      isIn: false,
      nom: 'rempl10',
      idGame: 'game',
      idParticipant: 'equipe'),
];
