import 'package:fscore/models/composition.dart';

List<JoueurComposition> kStrategie433 = [
  JoueurComposition(
      idComposition: 'C1' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player0',
      left: 160,
      top: 730),
  JoueurComposition(
      idComposition: 'C2' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player1',
      left: 300,
      top: 630),
  JoueurComposition(
      idComposition: 'C3' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player2',
      left: 206,
      top: 650),
  JoueurComposition(
      idComposition: 'C4' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player3',
      left: 122,
      top: 650),
  JoueurComposition(
      idComposition: 'C5' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player4',
      left: 20,
      top: 630),
  JoueurComposition(
      idComposition: 'C6' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player5',
      left: 280,
      top: 530),
  JoueurComposition(
      idComposition: 'C7' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player6',
      jaune: 0,
      left: 160,
      top: 540),
  JoueurComposition(
      idComposition: 'C8' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player7',
      left: 40,
      top: 530),
  JoueurComposition(
      idComposition: 'C9' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player8',
      left: 280,
      top: 420),
  JoueurComposition(
      idComposition: 'C10' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player9',
      left: 160,
      top: 430),
  JoueurComposition(
      idComposition: 'C11' + DateTime.now().millisecondsSinceEpoch.toString(),
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player10',
      left: 40,
      top: 420),
];
