import 'package:app/models/composition.dart';

List<JoueurComposition> kStrategie433 = [
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player0',
      left: 160,
      top: 730),
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player1',
      left: 300,
      top: 630),
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player2',
      left: 206,
      top: 650),
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player3',
      left: 122,
      top: 650),
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player4',
      left: 20,
      top: 630),
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player5',
      left: 280,
      top: 530),
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player6',
      jaune: 1,
      left: 160,
      top: 540),
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player7',
      left: 40,
      top: 530),
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player8',
      left: 280,
      top: 420),
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player9',
      left: 160,
      top: 430),
  JoueurComposition(
      isIn: true,
      idGame: 'game',
      idParticipant: 'equipe',
      idJoueur: 'joueur',
      numero: 0,
      nom: 'Player10',
      left: 40,
      top: 420),
];
