final List<Map<String, dynamic>> buts = [
  {
    "num": 1,
    "idJoueur": 13,
    "nomJoueur": "El-hadji Diallo",
    "team": "FC Hoderé Bamtaaré",
    "idTeam": 28,
    "idParticipant": 28,
    "nomEquipe": "FC Hoderé Bamtaaré",
    "idGame": 4,
    "homeGame": "27",
    "awayGame": "28",
    "dateGame": "2023-08-09",
    "minute": "",
    "idBut": 8,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 7
  },
  {
    "num": 2,
    "idJoueur": 27,
    "nomJoueur": "Sada Kelly",
    "team": "FC Piindi Bamtaaré",
    "idTeam": 30,
    "idParticipant": 30,
    "nomEquipe": "FC Piindi Bamtaaré",
    "idGame": 48,
    "homeGame": "34",
    "awayGame": "30",
    "dateGame": "2023-08-14",
    "minute": "",
    "idBut": 9,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 6
  },
  {
    "num": 3,
    "idJoueur": 10,
    "nomJoueur": "Issa Dia",
    "team": "FC Piindi Bamtaaré",
    "idTeam": 30,
    "idParticipant": 30,
    "nomEquipe": "FC Piindi Bamtaaré",
    "idGame": 3,
    "homeGame": "30",
    "awayGame": "31",
    "dateGame": "2023-08-08",
    "minute": "",
    "idBut": 5,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 6
  },
  {
    "num": 4,
    "idJoueur": 84,
    "nomJoueur": "Adama Lam",
    "team": "FC Véterans",
    "idTeam": 29,
    "idParticipant": 29,
    "nomEquipe": "FC Véterans",
    "idGame": 40,
    "homeGame": "29",
    "awayGame": "27",
    "dateGame": "2023-09-03",
    "minute": "",
    "idBut": 50,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 4
  },
  {
    "num": 5,
    "idJoueur": 39,
    "nomJoueur": "Oumar Moussa",
    "team": "FC Véterans",
    "idTeam": 29,
    "idParticipant": 29,
    "nomEquipe": "FC Véterans",
    "idGame": 40,
    "homeGame": "29",
    "awayGame": "27",
    "dateGame": "2023-09-03",
    "minute": "",
    "idBut": 53,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 3
  },
  {
    "num": 6,
    "idJoueur": 6,
    "nomJoueur": "Amadou Daddé",
    "team": "FC Yakaaré Django",
    "idTeam": 25,
    "idParticipant": 25,
    "nomEquipe": "FC Yakaaré Django",
    "idGame": 1,
    "homeGame": "25",
    "awayGame": "26",
    "dateGame": "2023-08-06",
    "minute": null,
    "idBut": 2,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 3
  },
  {
    "num": 7,
    "idJoueur": 5,
    "nomJoueur": "Amadou cheick",
    "team": "FC Yakaaré Django",
    "idTeam": 25,
    "idParticipant": 25,
    "nomEquipe": "FC Yakaaré Django",
    "idGame": 1,
    "homeGame": "25",
    "awayGame": "26",
    "dateGame": "2023-08-06",
    "minute": null,
    "idBut": 1,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 3
  },
  {
    "num": 8,
    "idJoueur": 73,
    "nomJoueur": "Oumar Amadou",
    "team": "FC Yakaaré",
    "idTeam": 26,
    "idParticipant": 26,
    "nomEquipe": "FC Yakaaré",
    "idGame": 44,
    "homeGame": "26",
    "awayGame": "29",
    "dateGame": "2023-09-18",
    "minute": "",
    "idBut": 72,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 2
  },
  {
    "num": 9,
    "idJoueur": 12,
    "nomJoueur": "Alsane Bellel",
    "team": "FC Lewlewal",
    "idTeam": 31,
    "idParticipant": 31,
    "nomEquipe": "FC Lewlewal",
    "idGame": 43,
    "homeGame": "31",
    "awayGame": "32",
    "dateGame": "2023-08-17",
    "minute": "",
    "idBut": 32,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 2
  },
  {
    "num": 10,
    "idJoueur": 43,
    "nomJoueur": "Adama Lam",
    "team": "FC Hodere Yontaabé",
    "idTeam": 27,
    "idParticipant": 27,
    "nomEquipe": "FC Hodere Yontaabé",
    "idGame": 34,
    "homeGame": "27",
    "awayGame": "26",
    "dateGame": "2023-08-16",
    "minute": "",
    "idBut": 30,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 2
  },
  {
    "num": 11,
    "idJoueur": 41,
    "nomJoueur": "Hamodou Syel",
    "team": "FC Hodere Yontaabé",
    "idTeam": 27,
    "idParticipant": 27,
    "nomEquipe": "FC Hodere Yontaabé",
    "idGame": 34,
    "homeGame": "27",
    "awayGame": "26",
    "dateGame": "2023-08-16",
    "minute": "",
    "idBut": 27,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 2
  },
  {
    "num": 12,
    "idJoueur": 37,
    "nomJoueur": "Thierno Lamine",
    "team": "FC Yakaaré Django",
    "idTeam": 25,
    "idParticipant": 25,
    "nomEquipe": "FC Yakaaré Django",
    "idGame": 33,
    "homeGame": "29",
    "awayGame": "25",
    "dateGame": "2023-08-15",
    "minute": "",
    "idBut": 26,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 2
  },
  {
    "num": 13,
    "idJoueur": 31,
    "nomJoueur": "Mika Diallo",
    "team": "FC Abou Sem",
    "idTeam": 34,
    "idParticipant": 34,
    "nomEquipe": "FC Abou Sem",
    "idGame": 48,
    "homeGame": "34",
    "awayGame": "30",
    "dateGame": "2023-08-14",
    "minute": "",
    "idBut": 15,
    "codeEdition": "thialgou2023",
    "codeMarque": "penalty",
    "nomMarque": "But sur penalty",
    "typeMarque": "propre",
    "nombre": 2
  },
  {
    "num": 14,
    "idJoueur": 29,
    "nomJoueur": "Mocktar Dia",
    "team": "FC Piindi Bamtaaré",
    "idTeam": 30,
    "idParticipant": 30,
    "nomEquipe": "FC Piindi Bamtaaré",
    "idGame": 48,
    "homeGame": "34",
    "awayGame": "30",
    "dateGame": "2023-08-14",
    "minute": "",
    "idBut": 14,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 2
  },
  {
    "num": 15,
    "idJoueur": 33,
    "nomJoueur": "Harouna",
    "team": "FC Foyré Bamtaaré",
    "idTeam": 33,
    "idParticipant": 33,
    "nomEquipe": "FC Foyré Bamtaaré",
    "idGame": 32,
    "homeGame": "32",
    "awayGame": "33",
    "dateGame": "2023-08-10",
    "minute": "",
    "idBut": 18,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 2
  },
  {
    "num": 16,
    "idJoueur": 11,
    "nomJoueur": "Athoumani",
    "team": "FC Piindi Bamtaaré",
    "idTeam": 30,
    "idParticipant": 30,
    "nomEquipe": "FC Piindi Bamtaaré",
    "idGame": 3,
    "homeGame": "30",
    "awayGame": "31",
    "dateGame": "2023-08-08",
    "minute": "",
    "idBut": 6,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 2
  },
  {
    "num": 17,
    "idJoueur": 94,
    "nomJoueur": "Ablaye Diallo",
    "team": "FC Yakaaré",
    "idTeam": 26,
    "idParticipant": 29,
    "nomEquipe": "FC Véterans",
    "idGame": 44,
    "homeGame": "26",
    "awayGame": "29",
    "dateGame": "2023-09-18",
    "minute": "",
    "idBut": 75,
    "codeEdition": "thialgou2023",
    "codeMarque": "butcontre",
    "nomMarque": "But Contre son Camp",
    "typeMarque": "contre",
    "nombre": 1
  },
  {
    "num": 18,
    "idJoueur": 92,
    "nomJoueur": "Demba Gacko",
    "team": "FC Lewlewal",
    "idTeam": 31,
    "idParticipant": 31,
    "nomEquipe": "FC Lewlewal",
    "idGame": 77,
    "homeGame": "34",
    "awayGame": "31",
    "dateGame": "2023-09-15",
    "minute": 20,
    "idBut": 71,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 19,
    "idJoueur": 88,
    "nomJoueur": "El-hadji Bathié",
    "team": "FC Hoderé Bamtaaré",
    "idTeam": 28,
    "idParticipant": 28,
    "nomEquipe": "FC Hoderé Bamtaaré",
    "idGame": 42,
    "homeGame": "25",
    "awayGame": "28",
    "dateGame": "2023-09-14",
    "minute": "",
    "idBut": 62,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 20,
    "idJoueur": 90,
    "nomJoueur": "Oumar Kelly",
    "team": "FC Foyré Bamtaaré",
    "idTeam": 33,
    "idParticipant": 33,
    "nomEquipe": "FC Foyré Bamtaaré",
    "idGame": 41,
    "homeGame": "33",
    "awayGame": "30",
    "dateGame": "2023-09-13",
    "minute": "",
    "idBut": 69,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 21,
    "idJoueur": 86,
    "nomJoueur": "Momo Lam",
    "team": "FC Union",
    "idTeam": 32,
    "idParticipant": 32,
    "nomEquipe": "FC Union",
    "idGame": 35,
    "homeGame": "30",
    "awayGame": "32",
    "dateGame": "2023-09-06",
    "minute": "",
    "idBut": 60,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 22,
    "idJoueur": 21,
    "nomJoueur": "Ablaye Thillo",
    "team": "FC Union",
    "idTeam": 32,
    "idParticipant": 32,
    "nomEquipe": "FC Union",
    "idGame": 35,
    "homeGame": "30",
    "awayGame": "32",
    "dateGame": "2023-09-06",
    "minute": "",
    "idBut": 59,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 23,
    "idJoueur": 25,
    "nomJoueur": "Lass Sy",
    "team": "FC Piindi Bamtaaré",
    "idTeam": 30,
    "idParticipant": 30,
    "nomEquipe": "FC Piindi Bamtaaré",
    "idGame": 35,
    "homeGame": "30",
    "awayGame": "32",
    "dateGame": "2023-09-06",
    "minute": "",
    "idBut": 57,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 24,
    "idJoueur": 80,
    "nomJoueur": "Ciré Sy",
    "team": "FC Union",
    "idTeam": 32,
    "idParticipant": 32,
    "nomEquipe": "FC Union",
    "idGame": 72,
    "homeGame": "34",
    "awayGame": "32",
    "dateGame": "2023-08-29",
    "minute": "",
    "idBut": 49,
    "codeEdition": "thialgou2023",
    "codeMarque": "penalty",
    "nomMarque": "But sur penalty",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 25,
    "idJoueur": 70,
    "nomJoueur": "Ablaye Mattel",
    "team": "FC Hoderé Bamtaaré",
    "idTeam": 28,
    "idParticipant": 28,
    "nomEquipe": "FC Hoderé Bamtaaré",
    "idGame": 39,
    "homeGame": "26",
    "awayGame": "28",
    "dateGame": "2023-08-25",
    "minute": "",
    "idBut": 48,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 26,
    "idJoueur": 71,
    "nomJoueur": "Seydi Ly",
    "team": "FC Hoderé Bamtaaré",
    "idTeam": 28,
    "idParticipant": 28,
    "nomEquipe": "FC Hoderé Bamtaaré",
    "idGame": 39,
    "homeGame": "26",
    "awayGame": "28",
    "dateGame": "2023-08-25",
    "minute": "",
    "idBut": 47,
    "codeEdition": "thialgou2023",
    "codeMarque": "penalty",
    "nomMarque": "But sur penalty",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 27,
    "idJoueur": 64,
    "nomJoueur": "Hamet Lam",
    "team": "FC Foyré Bamtaaré",
    "idTeam": 33,
    "idParticipant": 33,
    "nomEquipe": "FC Foyré Bamtaaré",
    "idGame": 71,
    "homeGame": "33",
    "awayGame": "34",
    "dateGame": "2023-08-19",
    "minute": "",
    "idBut": 44,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 28,
    "idJoueur": 63,
    "nomJoueur": "Alsane NGaidé",
    "team": "FC Abou Sem",
    "idTeam": 34,
    "idParticipant": 33,
    "nomEquipe": "FC Foyré Bamtaaré",
    "idGame": 71,
    "homeGame": "33",
    "awayGame": "34",
    "dateGame": "2023-08-19",
    "minute": "",
    "idBut": 43,
    "codeEdition": "thialgou2023",
    "codeMarque": "butcontre",
    "nomMarque": "But Contre son Camp",
    "typeMarque": "contre",
    "nombre": 1
  },
  {
    "num": 29,
    "idJoueur": 24,
    "nomJoueur": "Bra NGaidé",
    "team": "FC Foyré Bamtaaré",
    "idTeam": 33,
    "idParticipant": 33,
    "nomEquipe": "FC Foyré Bamtaaré",
    "idGame": 71,
    "homeGame": "33",
    "awayGame": "34",
    "dateGame": "2023-08-19",
    "minute": "",
    "idBut": 41,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 30,
    "idJoueur": 59,
    "nomJoueur": "Aguibe Lam",
    "team": "FC Véterans",
    "idTeam": 29,
    "idParticipant": 29,
    "nomEquipe": "FC Véterans",
    "idGame": 36,
    "homeGame": "28",
    "awayGame": "29",
    "dateGame": "2023-08-18",
    "minute": "",
    "idBut": 39,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 31,
    "idJoueur": 58,
    "nomJoueur": "Ablaye Dédé",
    "team": "FC Véterans",
    "idTeam": 29,
    "idParticipant": 29,
    "nomEquipe": "FC Véterans",
    "idGame": 36,
    "homeGame": "28",
    "awayGame": "29",
    "dateGame": "2023-08-18",
    "minute": "",
    "idBut": 38,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 32,
    "idJoueur": 52,
    "nomJoueur": "Youssouf Dia",
    "team": "FC Union",
    "idTeam": 32,
    "idParticipant": 32,
    "nomEquipe": "FC Union",
    "idGame": 43,
    "homeGame": "31",
    "awayGame": "32",
    "dateGame": "2023-08-17",
    "minute": "",
    "idBut": 34,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 33,
    "idJoueur": 49,
    "nomJoueur": "Tidjani Diou",
    "team": "FC Lewlewal",
    "idTeam": 31,
    "idParticipant": 31,
    "nomEquipe": "FC Lewlewal",
    "idGame": 43,
    "homeGame": "31",
    "awayGame": "32",
    "dateGame": "2023-08-17",
    "minute": "",
    "idBut": 33,
    "codeEdition": "thialgou2023",
    "codeMarque": "penalty",
    "nomMarque": "But sur penalty",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 34,
    "idJoueur": 48,
    "nomJoueur": "Amadou Dia",
    "team": "FC Lewlewal",
    "idTeam": 31,
    "idParticipant": 31,
    "nomEquipe": "FC Lewlewal",
    "idGame": 43,
    "homeGame": "31",
    "awayGame": "32",
    "dateGame": "2023-08-17",
    "minute": "",
    "idBut": 31,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 35,
    "idJoueur": 42,
    "nomJoueur": "Abdoul",
    "team": "FC Hodere Yontaabé",
    "idTeam": 27,
    "idParticipant": 27,
    "nomEquipe": "FC Hodere Yontaabé",
    "idGame": 34,
    "homeGame": "27",
    "awayGame": "26",
    "dateGame": "2023-08-16",
    "minute": "",
    "idBut": 29,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 36,
    "idJoueur": 38,
    "nomJoueur": "Hamodou",
    "team": "FC Yakaaré Django",
    "idTeam": 25,
    "idParticipant": 25,
    "nomEquipe": "FC Yakaaré Django",
    "idGame": 33,
    "homeGame": "29",
    "awayGame": "25",
    "dateGame": "2023-08-15",
    "minute": "",
    "idBut": 22,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 37,
    "idJoueur": 36,
    "nomJoueur": "Mama Dia",
    "team": "FC Yakaaré Django",
    "idTeam": 25,
    "idParticipant": 25,
    "nomEquipe": "FC Yakaaré Django",
    "idGame": 33,
    "homeGame": "29",
    "awayGame": "25",
    "dateGame": "2023-08-15",
    "minute": "",
    "idBut": 21,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 38,
    "idJoueur": 35,
    "nomJoueur": "Abou Dia",
    "team": "FC Yakaaré Django",
    "idTeam": 25,
    "idParticipant": 25,
    "nomEquipe": "FC Yakaaré Django",
    "idGame": 33,
    "homeGame": "29",
    "awayGame": "25",
    "dateGame": "2023-08-15",
    "minute": "",
    "idBut": 20,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 39,
    "idJoueur": 9,
    "nomJoueur": "Baba Ciré",
    "team": "FC Piindi Bamtaaré",
    "idTeam": 30,
    "idParticipant": 30,
    "nomEquipe": "FC Piindi Bamtaaré",
    "idGame": 48,
    "homeGame": "34",
    "awayGame": "30",
    "dateGame": "2023-08-14",
    "minute": "",
    "idBut": 13,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 40,
    "idJoueur": 28,
    "nomJoueur": "Ibra NGaidé",
    "team": "FC Piindi Bamtaaré",
    "idTeam": 30,
    "idParticipant": 30,
    "nomEquipe": "FC Piindi Bamtaaré",
    "idGame": 48,
    "homeGame": "34",
    "awayGame": "30",
    "dateGame": "2023-08-14",
    "minute": "",
    "idBut": 12,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 41,
    "idJoueur": 34,
    "nomJoueur": "Ablaye Talll",
    "team": "FC Foyré Bamtaaré",
    "idTeam": 33,
    "idParticipant": 33,
    "nomEquipe": "FC Foyré Bamtaaré",
    "idGame": 32,
    "homeGame": "32",
    "awayGame": "33",
    "dateGame": "2023-08-10",
    "minute": "",
    "idBut": 19,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  },
  {
    "num": 42,
    "idJoueur": 32,
    "nomJoueur": "Babo Sy",
    "team": "FC Foyré Bamtaaré",
    "idTeam": 33,
    "idParticipant": 33,
    "nomEquipe": "FC Foyré Bamtaaré",
    "idGame": 32,
    "homeGame": "32",
    "awayGame": "33",
    "dateGame": "2023-08-10",
    "minute": "",
    "idBut": 16,
    "codeEdition": "thialgou2023",
    "codeMarque": "but",
    "nomMarque": "But",
    "typeMarque": "propre",
    "nombre": 1
  }
];
