import 'package:app/models/joueur.dart';
import 'package:app/models/participant.dart';
import 'package:app/service/local_service.dart';

class JoueurService {
  static LocalService get service => LocalService('joueur.json');

  static Future<List<Joueur>?> getLocalData(
      List<Participant> participants) async {
    if (await service.fileExists()) {
      final List? data = (await service.getData());
      if (data != null)
        return data
            .where((element) => participants.any(
                (e) => e.idParticipant == element['idParticipant'].toString()))
            .map((e) {
          Participant participant = participants.singleWhere((element) =>
              element.idParticipant == e['idParticipant'].toString());
          return Joueur.fromJson(e, participant);
        }).toList();
    }
    return null;
  }

  Future<List<Joueur>> getData(List<Participant> participants) async {
    if (await service.isLoadable())
      return await getLocalData(participants) ?? [];
    await Future.delayed(const Duration(seconds: 1));
    // Todo changer joueur par remote data
    await service.setData(joueurs);
    return joueurs
        .where((element) => participants
            .any((e) => e.idParticipant == element['idParticipant'].toString()))
        .map((e) {
      Participant participant = participants.singleWhere(
          (element) => element.idParticipant == e['idParticipant'].toString());
      return Joueur.fromJson(e, participant);
    }).toList();
  }
}

final List<Map<String, dynamic>> joueurs = [
  {
    "idJoueur": 35,
    "nomJoueur": "Abou Dia",
    "idParticipant": 25,
    "localiteJoueur": "",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "vitesse": 10.0,
    "poids": 54.0,
    "taille": 1.65,
    "rating": 1,
    "dateNaissance": '2007-02-01',
  },
  {
    "idJoueur": 66,
    "nomJoueur": "Abou Sy",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 8,
    "nomJoueur": "Alsane Yall",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 65,
    "nomJoueur": "Amadou Baidi",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 6,
    "nomJoueur": "Amadou Daddé",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 5,
    "nomJoueur": "Amadou cheick",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 38,
    "nomJoueur": "Hamodou",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 7,
    "nomJoueur": "Lass Lam",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 36,
    "nomJoueur": "Mama Dia",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 89,
    "nomJoueur": "Mamadou Mayi",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 37,
    "nomJoueur": "Thierno Lamine",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 42,
    "nomJoueur": "Abdoul",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 43,
    "nomJoueur": "Adama Lam",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 46,
    "nomJoueur": "Babo Ba",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 68,
    "nomJoueur": "Babo Kane",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 47,
    "nomJoueur": "Bouckari Thiam",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 44,
    "nomJoueur": "Hamet NGaidé",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 41,
    "nomJoueur": "Hamodou Syel",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 17,
    "nomJoueur": "Kao Sy",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 67,
    "nomJoueur": "Kassoum Gacko",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 45,
    "nomJoueur": "Mama Bara",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 18,
    "nomJoueur": "Mao",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 2,
    "nomJoueur": "Ablaye Yall",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 1,
    "nomJoueur": "El'hadj Syleyman",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 3,
    "nomJoueur": "Kawo Sy",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 72,
    "nomJoueur": "Mahamodou",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 74,
    "nomJoueur": "Nalla Gacko",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 4,
    "nomJoueur": "Niga",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 73,
    "nomJoueur": "Oumar Amadou",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 70,
    "nomJoueur": "Ablaye Mattel",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 55,
    "nomJoueur": "Amadou Daoude",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 16,
    "nomJoueur": "Amadou Siley",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 15,
    "nomJoueur": "Baba Ciré",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 54,
    "nomJoueur": "Babo Djeya",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 75,
    "nomJoueur": "Bouckary Lam",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 53,
    "nomJoueur": "Courtois",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 88,
    "nomJoueur": "El-hadji Bathié",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 13,
    "nomJoueur": "El-hadji Diallo",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 60,
    "nomJoueur": "Mamadou Ba",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 76,
    "nomJoueur": "Mamadou Sy",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 14,
    "nomJoueur": "Salif Ba",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 71,
    "nomJoueur": "Seydi Ly",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 94,
    "nomJoueur": "Ablaye Diallo",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 58,
    "nomJoueur": "Ablaye Dédé",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 84,
    "nomJoueur": "Adama Lam",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 59,
    "nomJoueur": "Aguibe Lam",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 56,
    "nomJoueur": "Demba",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 40,
    "nomJoueur": "Lass Lam",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 57,
    "nomJoueur": "Mocktar Sy",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 39,
    "nomJoueur": "Oumar Moussa",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 11,
    "nomJoueur": "Athoumani",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 9,
    "nomJoueur": "Baba Ciré",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 87,
    "nomJoueur": "Bocar Lam",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 28,
    "nomJoueur": "Ibra NGaidé",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 10,
    "nomJoueur": "Issa Dia",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 25,
    "nomJoueur": "Lass Sy",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 29,
    "nomJoueur": "Mocktar Dia",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 27,
    "nomJoueur": "Sada Kelly",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 26,
    "nomJoueur": "Souaibe",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 85,
    "nomJoueur": "Thierno Dia",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 21,
    "nomJoueur": "Ablaye Thillo",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 20,
    "nomJoueur": "Alssane Amadou",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 82,
    "nomJoueur": "Aly Sada",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 51,
    "nomJoueur": "Baba Daddé",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 80,
    "nomJoueur": "Ciré Sy",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 86,
    "nomJoueur": "Momo Lam",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 83,
    "nomJoueur": "Moussa",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 22,
    "nomJoueur": "Thierno Samba",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 52,
    "nomJoueur": "Youssouf Dia",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 12,
    "nomJoueur": "Alsane Bellel",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 48,
    "nomJoueur": "Amadou Dia",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 78,
    "nomJoueur": "Cheikh Baye",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 92,
    "nomJoueur": "Demba Gacko",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 50,
    "nomJoueur": "Hamidou NGaidé",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 77,
    "nomJoueur": "Mama Raki",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 79,
    "nomJoueur": "Papi",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 49,
    "nomJoueur": "Tidjani Diou",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 34,
    "nomJoueur": "Ablaye Talll",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 19,
    "nomJoueur": "Aliou Dia",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 63,
    "nomJoueur": "Alsane NGaidé",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 23,
    "nomJoueur": "Amadou dialade",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 32,
    "nomJoueur": "Babo Sy",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 24,
    "nomJoueur": "Bra NGaidé",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 62,
    "nomJoueur": "Gawde NGaidé",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 61,
    "nomJoueur": "Hamadi Dia",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 64,
    "nomJoueur": "Hamet Lam",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 33,
    "nomJoueur": "Harouna",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 90,
    "nomJoueur": "Oumar Kelly",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 31,
    "nomJoueur": "Mika Diallo",
    "idParticipant": 34,
    "localiteJoueur": "thialgou",
    "idEquipe": 35,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Abou Sem",
    "libelleEquipe": "Abou Sem",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  },
  {
    "idJoueur": 30,
    "nomJoueur": "Zakaria Sy",
    "idParticipant": 34,
    "localiteJoueur": "thialgou",
    "idEquipe": 35,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Abou Sem",
    "libelleEquipe": "Abou Sem",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou"
  }
];
