import 'package:app/models/event.dart';
import 'package:app/service/local_service.dart';

class SanctionService {
  static LocalService get service => LocalService('sanction.json');

  static Future<List<CardEvent>?> getLocalData() async {
    if (await service.fileExists()) {
      final List? data = (await service.getData());
      if (data != null) return data.map((e) => CardEvent.fromJson(e)).toList();
    }
    return null;
  }

  static Future<List<CardEvent>> getData({bool remote = false}) async {
    final List<CardEvent> data = await getRemoteData();
    if (data.isEmpty && await service.hasData())
      return await getLocalData() ?? [];
    return data;
  }

  static Future<List<CardEvent>> getRemoteData() async {
    try {
      await Future.delayed(const Duration(seconds: 1));
      if (sanctions.isNotEmpty) await service.setData(sanctions);
      return sanctions.map((e) => CardEvent.fromJson(e)).toList();
    } catch (e) {
      return [];
    }
  }

  static Future<bool> addCardEvent(CardEvent arbitre) async {
    sanctions.add(arbitre.toJson());
    return true;
  }

  static Future<bool> editCardEvent(String idBut, CardEvent arbitre) async {
    if (sanctions.any((element) => element['idBut'] == idBut)) {
      int index = sanctions.indexWhere((element) => element['idBut'] == idBut);
      if (index >= 0) sanctions[index] = arbitre.toJson();
      return true;
    }
    return false;
  }

  static Future<bool> deleteCardEvent(String idBut) async {
    if (sanctions.any((element) => element['idBut'] == idBut)) {
      sanctions.removeWhere((element) => element['idBut'] == idBut);
      return true;
    }
    return true;
  }
}

final List<Map<String, dynamic>> sanctions = [
  {
    "nombreCarton": 1,
    "idSanctionner": 1,
    "idJoueur": 1,
    "idGame": 1,
    "codeSanction": "jaune",
    "minute": 15,
    "nomJoueur": "El'hadj Syleyman",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "26",
    "dateGame": "2023-08-06",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 2,
    "idJoueur": 2,
    "idGame": 1,
    "codeSanction": "jaune",
    "minute": 32,
    "nomJoueur": "Ablaye Yall",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "26",
    "dateGame": "2023-08-06",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 3,
    "idJoueur": 3,
    "idGame": 1,
    "codeSanction": "jaune",
    "minute": 16,
    "nomJoueur": "Kawo Sy",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "26",
    "dateGame": "2023-08-06",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 5,
    "idJoueur": 4,
    "idGame": 1,
    "codeSanction": "rougeetsanction",
    "minute": 60,
    "nomJoueur": "Niga",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Rouge et Sanction",
    "typeSanction": "suspension",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "26",
    "dateGame": "2023-08-06",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": "2",
    "motif": "Carton rouge et sanction disciplinaire"
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 6,
    "idJoueur": 7,
    "idGame": 1,
    "codeSanction": "jaune",
    "minute": 46,
    "nomJoueur": "Lass Lam",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "26",
    "dateGame": "2023-08-06",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 7,
    "idJoueur": 8,
    "idGame": 1,
    "codeSanction": "jaune",
    "minute": 48,
    "nomJoueur": "Alsane Yall",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "26",
    "dateGame": "2023-08-06",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 9,
    "idJoueur": 9,
    "idGame": 3,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Baba Ciré",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "30",
    "awayGame": "31",
    "dateGame": "2023-08-08",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 10,
    "idJoueur": 12,
    "idGame": 3,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Alsane Bellel",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "30",
    "awayGame": "31",
    "dateGame": "2023-08-08",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 11,
    "idJoueur": 17,
    "idGame": 4,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Kao Sy",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "28",
    "dateGame": "2023-08-09",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 12,
    "idJoueur": 18,
    "idGame": 4,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Mao",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "28",
    "dateGame": "2023-08-09",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 13,
    "idJoueur": 14,
    "idGame": 4,
    "codeSanction": "rougeetsanction",
    "minute": "",
    "nomJoueur": "Salif Ba",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Rouge et Sanction",
    "typeSanction": "suspension",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "28",
    "dateGame": "2023-08-09",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": "2",
    "motif": "Carton rouge et sanction disciplinaire"
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 14,
    "idJoueur": 16,
    "idGame": 4,
    "codeSanction": "rouge",
    "minute": "",
    "nomJoueur": "Amadou Siley",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Rouge",
    "typeSanction": "suspension",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "28",
    "dateGame": "2023-08-09",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 15,
    "idJoueur": 15,
    "idGame": 4,
    "codeSanction": "sanction",
    "minute": "",
    "nomJoueur": "Baba Ciré",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Sanction Administrative",
    "typeSanction": "suspension",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "28",
    "dateGame": "2023-08-09",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": "1",
    "motif": "Mauvais comportement  vers les arbitre aprés la fin du match"
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 16,
    "idJoueur": 19,
    "idGame": 32,
    "codeSanction": "rougedirect",
    "minute": "",
    "nomJoueur": "Aliou Dia",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Rouge Direct",
    "typeSanction": "suspension",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "32",
    "awayGame": "33",
    "dateGame": "2023-08-10",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 17,
    "idJoueur": 20,
    "idGame": 32,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Alssane Amadou",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "32",
    "awayGame": "33",
    "dateGame": "2023-08-10",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 18,
    "idJoueur": 21,
    "idGame": 32,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Ablaye Thillo",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "32",
    "awayGame": "33",
    "dateGame": "2023-08-10",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 19,
    "idJoueur": 22,
    "idGame": 32,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Thierno Samba",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "32",
    "awayGame": "33",
    "dateGame": "2023-08-10",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 20,
    "idJoueur": 23,
    "idGame": 32,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Amadou dialade",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "32",
    "awayGame": "33",
    "dateGame": "2023-08-10",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 21,
    "idJoueur": 24,
    "idGame": 32,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Bra NGaidé",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "32",
    "awayGame": "33",
    "dateGame": "2023-08-10",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 22,
    "idJoueur": 26,
    "idGame": 48,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Souaibe",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "34",
    "awayGame": "30",
    "dateGame": "2023-08-14",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 23,
    "idJoueur": 25,
    "idGame": 48,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Lass Sy",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "34",
    "awayGame": "30",
    "dateGame": "2023-08-14",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 24,
    "idJoueur": 30,
    "idGame": 48,
    "codeSanction": "jaune",
    "minute": 46,
    "nomJoueur": "Zakaria Sy",
    "idParticipant": 34,
    "localiteJoueur": "thialgou",
    "idEquipe": 35,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Abou Sem",
    "libelleEquipe": "Abou Sem",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "34",
    "awayGame": "30",
    "dateGame": "2023-08-14",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 25,
    "idJoueur": 39,
    "idGame": 33,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Oumar Moussa",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "29",
    "awayGame": "25",
    "dateGame": "2023-08-15",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 26,
    "idJoueur": 40,
    "idGame": 33,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Lass Lam",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "29",
    "awayGame": "25",
    "dateGame": "2023-08-15",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 27,
    "idJoueur": 35,
    "idGame": 33,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Abou Dia",
    "idParticipant": 25,
    "localiteJoueur": "",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "29",
    "awayGame": "25",
    "dateGame": "2023-08-15",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 28,
    "idJoueur": 7,
    "idGame": 33,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Lass Lam",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "29",
    "awayGame": "25",
    "dateGame": "2023-08-15",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr1",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 29,
    "idJoueur": 1,
    "idGame": 34,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "El'hadj Syleyman",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "26",
    "dateGame": "2023-08-16",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 30,
    "idJoueur": 44,
    "idGame": 34,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Hamet NGaidé",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "26",
    "dateGame": "2023-08-16",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 31,
    "idJoueur": 45,
    "idGame": 34,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Mama Bara",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "26",
    "dateGame": "2023-08-16",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 32,
    "idJoueur": 18,
    "idGame": 34,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Mao",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "26",
    "dateGame": "2023-08-16",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 33,
    "idJoueur": 46,
    "idGame": 34,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Babo Ba",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "26",
    "dateGame": "2023-08-16",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 34,
    "idJoueur": 47,
    "idGame": 34,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Bouckari Thiam",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "27",
    "awayGame": "26",
    "dateGame": "2023-08-16",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 35,
    "idJoueur": 12,
    "idGame": 43,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Alsane Bellel",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "31",
    "awayGame": "32",
    "dateGame": "2023-08-17",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 36,
    "idJoueur": 50,
    "idGame": 43,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Hamidou NGaidé",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "31",
    "awayGame": "32",
    "dateGame": "2023-08-17",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 37,
    "idJoueur": 21,
    "idGame": 43,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Ablaye Thillo",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "31",
    "awayGame": "32",
    "dateGame": "2023-08-17",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 38,
    "idJoueur": 51,
    "idGame": 43,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Baba Daddé",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "31",
    "awayGame": "32",
    "dateGame": "2023-08-17",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 39,
    "idJoueur": 56,
    "idGame": 36,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Demba",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "28",
    "awayGame": "29",
    "dateGame": "2023-08-18",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 40,
    "idJoueur": 57,
    "idGame": 36,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Mocktar Sy",
    "idParticipant": 29,
    "localiteJoueur": "thialgou",
    "idEquipe": 30,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Véterans",
    "libelleEquipe": "Véterans",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "28",
    "awayGame": "29",
    "dateGame": "2023-08-18",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 41,
    "idJoueur": 53,
    "idGame": 36,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Courtois",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "28",
    "awayGame": "29",
    "dateGame": "2023-08-18",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 42,
    "idJoueur": 54,
    "idGame": 36,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Babo Djeya",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "28",
    "awayGame": "29",
    "dateGame": "2023-08-18",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 43,
    "idJoueur": 55,
    "idGame": 36,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Amadou Daoude",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "28",
    "awayGame": "29",
    "dateGame": "2023-08-18",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 44,
    "idJoueur": 13,
    "idGame": 36,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "El-hadji Diallo",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "28",
    "awayGame": "29",
    "dateGame": "2023-08-18",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 45,
    "idJoueur": 53,
    "idGame": 36,
    "codeSanction": "rougedirect",
    "minute": "",
    "nomJoueur": "Courtois",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Rouge Direct",
    "typeSanction": "suspension",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "28",
    "awayGame": "29",
    "dateGame": "2023-08-18",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 46,
    "idJoueur": 60,
    "idGame": 36,
    "codeSanction": "rougedirect",
    "minute": "",
    "nomJoueur": "Mamadou Ba",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Rouge Direct",
    "typeSanction": "suspension",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "28",
    "awayGame": "29",
    "dateGame": "2023-08-18",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 48,
    "idJoueur": 62,
    "idGame": 71,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Gawde NGaidé",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "33",
    "awayGame": "34",
    "dateGame": "2023-08-19",
    "heureGame": "17:00",
    "stadeGame": "Stade de thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 49,
    "idJoueur": 61,
    "idGame": 71,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Hamadi Dia",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "33",
    "awayGame": "34",
    "dateGame": "2023-08-19",
    "heureGame": "17:00",
    "stadeGame": "Stade de thialgou",
    "codeNiveau": "tr2",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 50,
    "idJoueur": 17,
    "idGame": 37,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Kao Sy",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "27",
    "dateGame": "2023-08-23",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 51,
    "idJoueur": 67,
    "idGame": 37,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Kassoum Gacko",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "27",
    "dateGame": "2023-08-23",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 52,
    "idJoueur": 44,
    "idGame": 37,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Hamet NGaidé",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "27",
    "dateGame": "2023-08-23",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 53,
    "idJoueur": 68,
    "idGame": 37,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Babo Kane",
    "idParticipant": 27,
    "localiteJoueur": "thialgou",
    "idEquipe": 27,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hodere Yontaabé",
    "libelleEquipe": "Hodere Yontaabé",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "27",
    "dateGame": "2023-08-23",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 54,
    "idJoueur": 65,
    "idGame": 37,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Amadou Baidi",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "27",
    "dateGame": "2023-08-23",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 55,
    "idJoueur": 66,
    "idGame": 37,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Abou Sy",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "27",
    "dateGame": "2023-08-23",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 56,
    "idJoueur": 72,
    "idGame": 39,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Mahamodou",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "26",
    "awayGame": "28",
    "dateGame": "2023-08-25",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 57,
    "idJoueur": 73,
    "idGame": 39,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Oumar Amadou",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "26",
    "awayGame": "28",
    "dateGame": "2023-08-25",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 58,
    "idJoueur": 74,
    "idGame": 39,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Nalla Gacko",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "26",
    "awayGame": "28",
    "dateGame": "2023-08-25",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 59,
    "idJoueur": 3,
    "idGame": 39,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Kawo Sy",
    "idParticipant": 26,
    "localiteJoueur": "thialgou",
    "idEquipe": 28,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré",
    "libelleEquipe": "Yakaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "26",
    "awayGame": "28",
    "dateGame": "2023-08-25",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 60,
    "idJoueur": 75,
    "idGame": 39,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Bouckary Lam",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "26",
    "awayGame": "28",
    "dateGame": "2023-08-25",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 61,
    "idJoueur": 76,
    "idGame": 39,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Mamadou Sy",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "26",
    "awayGame": "28",
    "dateGame": "2023-08-25",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 62,
    "idJoueur": 50,
    "idGame": 38,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Hamidou NGaidé",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "31",
    "awayGame": "33",
    "dateGame": "2023-08-27",
    "heureGame": "17:30",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 63,
    "idJoueur": 77,
    "idGame": 38,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Mama Raki",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "31",
    "awayGame": "33",
    "dateGame": "2023-08-27",
    "heureGame": "17:30",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 64,
    "idJoueur": 79,
    "idGame": 38,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Papi",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "31",
    "awayGame": "33",
    "dateGame": "2023-08-27",
    "heureGame": "17:30",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 65,
    "idJoueur": 63,
    "idGame": 38,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Alsane NGaidé",
    "idParticipant": 33,
    "localiteJoueur": "thialgou",
    "idEquipe": 34,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Foyré Bamtaaré",
    "libelleEquipe": "Foyré Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "31",
    "awayGame": "33",
    "dateGame": "2023-08-27",
    "heureGame": "17:30",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 66,
    "idJoueur": 82,
    "idGame": 72,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Aly Sada",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "34",
    "awayGame": "32",
    "dateGame": "2023-08-29",
    "heureGame": "17:00",
    "stadeGame": "Stade de thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 67,
    "idJoueur": 51,
    "idGame": 72,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Baba Daddé",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "34",
    "awayGame": "32",
    "dateGame": "2023-08-29",
    "heureGame": "17:00",
    "stadeGame": "Stade de thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 68,
    "idJoueur": 80,
    "idGame": 72,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Ciré Sy",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "34",
    "awayGame": "32",
    "dateGame": "2023-08-29",
    "heureGame": "17:00",
    "stadeGame": "Stade de thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 69,
    "idJoueur": 83,
    "idGame": 72,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Moussa",
    "idParticipant": 32,
    "localiteJoueur": "thialgou",
    "idEquipe": 32,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Union",
    "libelleEquipe": "Union",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "34",
    "awayGame": "32",
    "dateGame": "2023-08-29",
    "heureGame": "17:00",
    "stadeGame": "Stade de thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 70,
    "idJoueur": 78,
    "idGame": 38,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Cheikh Baye",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "31",
    "awayGame": "33",
    "dateGame": "2023-08-27",
    "heureGame": "17:30",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 71,
    "idJoueur": 26,
    "idGame": 35,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Souaibe",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "30",
    "awayGame": "32",
    "dateGame": "2023-09-06",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 72,
    "idJoueur": 85,
    "idGame": 35,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Thierno Dia",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "30",
    "awayGame": "32",
    "dateGame": "2023-09-06",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 73,
    "idJoueur": 25,
    "idGame": 41,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Lass Sy",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "33",
    "awayGame": "30",
    "dateGame": "2023-09-13",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr4",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 74,
    "idJoueur": 27,
    "idGame": 41,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Sada Kelly",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "33",
    "awayGame": "30",
    "dateGame": "2023-09-13",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr4",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 75,
    "idJoueur": 87,
    "idGame": 41,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Bocar Lam",
    "idParticipant": 30,
    "localiteJoueur": "thialgou",
    "idEquipe": 31,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Piindi Bamtaaré",
    "libelleEquipe": "Piindi Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "33",
    "awayGame": "30",
    "dateGame": "2023-09-13",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr4",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 76,
    "idJoueur": 71,
    "idGame": 42,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Seydi Ly",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "28",
    "dateGame": "2023-09-14",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr4",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 77,
    "idJoueur": 88,
    "idGame": 42,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "El-hadji Bathié",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "28",
    "dateGame": "2023-09-14",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr4",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 78,
    "idJoueur": 36,
    "idGame": 42,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Mama Dia",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "28",
    "dateGame": "2023-09-14",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr4",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 79,
    "idJoueur": 89,
    "idGame": 42,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Mamadou Mayi",
    "idParticipant": 25,
    "localiteJoueur": "thialgou",
    "idEquipe": 26,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Yakaaré Django",
    "libelleEquipe": "Yakaaré Django",
    "localiteEquipe": "Thialgou",
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "28",
    "dateGame": "2023-09-14",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr4",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 80,
    "idJoueur": 15,
    "idGame": 42,
    "codeSanction": "rougedirect",
    "minute": "",
    "nomJoueur": "Baba Ciré",
    "idParticipant": 28,
    "localiteJoueur": "thialgou",
    "idEquipe": 29,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Hoderé Bamtaaré",
    "libelleEquipe": "Hoderé Bamtaaré",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Rouge Direct",
    "typeSanction": "suspension",
    "idGroupe": 9,
    "nomGroupe": "A",
    "codePhase": "grp",
    "homeGame": "25",
    "awayGame": "28",
    "dateGame": "2023-09-14",
    "heureGame": "17:00",
    "stadeGame": "Stade de Thialgou",
    "codeNiveau": "tr4",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 81,
    "idJoueur": 78,
    "idGame": 77,
    "codeSanction": "jaune",
    "minute": "",
    "nomJoueur": "Cheikh Baye",
    "idParticipant": 31,
    "localiteJoueur": "thialgou",
    "idEquipe": 33,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Lewlewal",
    "libelleEquipe": "Lewlewal",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "34",
    "awayGame": "31",
    "dateGame": "2023-09-15",
    "heureGame": "17:00",
    "stadeGame": "Stade de thialgou",
    "codeNiveau": "tr4",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 82,
    "idJoueur": 31,
    "idGame": 77,
    "codeSanction": "jaune",
    "minute": 20,
    "nomJoueur": "Mika Diallo",
    "idParticipant": 34,
    "localiteJoueur": "thialgou",
    "idEquipe": 35,
    "idEdition": "thialgou2023",
    "nomEquipe": "FC Abou Sem",
    "libelleEquipe": "Abou Sem",
    "localiteEquipe": null,
    "codeEdition": "thialgou2023",
    "anneeEdition": "2023",
    "nomEdition": "Tournoi Pélle Thialgou Edition 2023",
    "codeCompetition": "thialgou",
    "nomCompetition": "Tournoi Pellé Thialgou Edition 2023",
    "localiteCompetition": "Thialgou",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 10,
    "nomGroupe": "B",
    "codePhase": "grp",
    "homeGame": "34",
    "awayGame": "31",
    "dateGame": "2023-09-15",
    "heureGame": "17:00",
    "stadeGame": "Stade de thialgou",
    "codeNiveau": "tr4",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 84,
    "idJoueur": 95,
    "idGame": 89,
    "codeSanction": "jaune",
    "minute": 56,
    "nomJoueur": "Idrissa Thiam",
    "idParticipant": 35,
    "localiteJoueur": "Afrique",
    "idEquipe": 36,
    "idEdition": "can2024",
    "nomEquipe": "Mauritanie",
    "libelleEquipe": "Mauritanie",
    "localiteEquipe": "Afrique",
    "codeEdition": "can2024",
    "anneeEdition": "2023",
    "nomEdition": "Coupe d'Afrique des Nations  2023",
    "codeCompetition": "can",
    "nomCompetition": "Coupe d'afrique des Nations",
    "localiteCompetition": "africa",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 19,
    "nomGroupe": "E",
    "codePhase": "grp",
    "homeGame": "35",
    "awayGame": "38",
    "dateGame": "2024-02-16",
    "heureGame": "16:00",
    "stadeGame": "Stade",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  },
  {
    "nombreCarton": 1,
    "idSanctionner": 85,
    "idJoueur": 95,
    "idGame": 89,
    "codeSanction": "jaune",
    "minute": 50,
    "nomJoueur": "Idrissa Thiam",
    "idParticipant": 35,
    "localiteJoueur": "Afrique",
    "idEquipe": 36,
    "idEdition": "can2024",
    "nomEquipe": "Mauritanie",
    "libelleEquipe": "Mauritanie",
    "localiteEquipe": "Afrique",
    "codeEdition": "can2024",
    "anneeEdition": "2023",
    "nomEdition": "Coupe d'Afrique des Nations  2023",
    "codeCompetition": "can",
    "nomCompetition": "Coupe d'afrique des Nations",
    "localiteCompetition": "africa",
    "nomSanction": "Carton Jaune",
    "typeSanction": "avertissement",
    "idGroupe": 19,
    "nomGroupe": "E",
    "codePhase": "grp",
    "homeGame": "35",
    "awayGame": "38",
    "dateGame": "2024-02-16",
    "heureGame": "16:00",
    "stadeGame": "Stade",
    "codeNiveau": "tr3",
    "nombreMatch": null,
    "motif": null
  }
];
