// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRkKUNohKSP3XoPM2HQbBUYiGlRe_dA8',
    appId: '1:196237042075:web:208a8d22f1174b3885813e',
    messagingSenderId: '196237042075',
    projectId: 'fscore-8d32b',
    authDomain: 'fscore-8d32b.firebaseapp.com',
    storageBucket: 'fscore-8d32b.appspot.com',
    measurementId: 'G-RYNP05YZ2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6t53xblII2lkI6jD1Qqgb3TctavsPtU',
    appId: '1:196237042075:android:8aae1cfa9241d9bc85813e',
    messagingSenderId: '196237042075',
    projectId: 'fscore-8d32b',
    storageBucket: 'fscore-8d32b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGzfJtHtX85g_CCcGz78XEvOmcKVmEz0',
    appId: '1:196237042075:ios:1281d5a378262f4b85813e',
    messagingSenderId: '196237042075',
    projectId: 'fscore-8d32b',
    storageBucket: 'fscore-8d32b.appspot.com',
    iosBundleId: 'com.fscore.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjGzfJtHtX85g_CCcGz78XEvOmcKVmEz0',
    appId: '1:196237042075:ios:1281d5a378262f4b85813e',
    messagingSenderId: '196237042075',
    projectId: 'fscore-8d32b',
    storageBucket: 'fscore-8d32b.appspot.com',
    iosBundleId: 'com.fscore.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4KfPPNky5uJ4xuOqXPbexutOKT3mM62A',
    appId: '1:196237042075:web:8dd56cd8d04c869285813e',
    messagingSenderId: '196237042075',
    projectId: 'fscore-8d32b',
    authDomain: 'fscore-8d32b.firebaseapp.com',
    storageBucket: 'fscore-8d32b.appspot.com',
    measurementId: 'G-E3FYWSNZP9',
  );
}
